### ISSUE TITLE
Using Object.assign

### ISSUE THREAD

**Issue by omaotzu** [sindresorhus/yn#19]
Object.assign isn't compatible with IE (surprise surprise)... If you're using yn on the front end might run into some issues where the package wont work

Issue arose on our end from using it in combination with Next js and using publicruntime config import config to the front end to feature switch certain actions and renders.

There are several ways round it (moving yn to the next build config etc etc) but thought I'd let you know!

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by omaotzu** [comment]
👍
