### ISSUE TITLE
Question about YN 4.0 Breaking change

### ISSUE THREAD

**Issue by eitah** [sindresorhus/yn#27]
I had a question about why this decision was chosen:
`Only use a CommonJS export for the TypeScript definition
You need to change import yn from 'yn'; to import yn = require('yn');`
Is the best practice now to disallow ECMASCRIPT imports as you have done in version 4 by not exposing import?

And what causes the `import yn =` syntax to work. Shouldn't it be `const yn = ` if it's true common-js?

**Comment by sindresorhus** [comment]
I'm not disallowing use in ESM. I'm just correcting a mistake. This module is CommonJS and that should be defined in the TypeScript file too.

See https://github.com/sindresorhus/mem/issues/31 for context.

---

> And what causes the import yn = syntax to work. Shouldn't it be const yn = if it's true common-js?

`import yn = require(…)` is a TypeScript only syntax.
