### ISSUE TITLE
Missing properties in package.json causing errors in monorepo

### ISSUE THREAD

**Issue by tkodev** [sindresorhus/yn#31]
Error:

- `Package subpath './package.json' is not defined by "exports" in /<app-path>/node_modules/yn/package.json`.
- In addition, author URL value is not a valid URI string. URI with a scheme is expected.

Solution:

Adopt this into package.json
```
"author": {
    ...
    "url": "https://sindresorhus.com"
},
"exports": {
    "./package.json": "./package.json",
},
```

**Comment by sindresorhus** [comment]
> Package subpath './package.json' is not defined by "exports" in /<app-path>/node_modules/yn/package.json.

The message is incorrect. This is a problem with the tool you're using, not this package.

**Comment by sindresorhus** [comment]
> In addition, author URL value is not a valid URI string. URI with a scheme is expected.

https://github.com/sindresorhus/yn/blob/b0f6903cda957757cabbeabdd17d2ecb2011e17c/package.json#L11
