### ISSUE TITLE
Yeah/Yup

### ISSUE THREAD

**Issue by saquibkhan** [sindresorhus/yn#5]
Are they valid? Should Yn identify these also?

test(function (t) {
	t.assert(yn('yup', {lenient: true}) === true);
	t.end();
});

**Comment by kevva** [comment]
Hm, why?

**Comment by saquibkhan** [comment]
above test fails.

**Comment by kevva** [comment]
I mean, why should we add `yup` and `yeah`?

**Comment by arthurvr** [comment]
> I mean, why should we add yup and yeah?

ping @saquibkhan?

**Comment by sindresorhus** [comment]
I just made a module that could be useful for this: https://github.com/sindresorhus/yes-no-words

**Comment by sindresorhus** [comment]
I'm asking. Should it be included in `yn`?

**Comment by kevva** [comment]
How many of them are truly useful? :P

**Comment by sindresorhus** [comment]
@kevva Very few, maybe `ya` and similar, but yeah, that's overdoing it.

**Comment by saquibkhan** [comment]
Yes, actually below test passed so i thought why others are not supported.

test(function (t) {
        t.assert(yn('yeah', {lenient: true}) === true);
        t.end();
});
